Feature: Render Board

  Scenario: Empty minefield
    When I run "minesweeper --size=[5,3]"
    Then it should pass with:
      """
      .....
      .....
      .....

      """

  Scenario: Place Single Mine on small Gameboard
    When I run "minesweeper --size=[3,2] --mines=[[2,1]]"
    Then it should pass with:
      """
      1*1
      111

      """

  Scenario: Place Single Mine on large Gameboard
    When I run "minesweeper --size=[12,6] --mines=[[5,4]]"
    Then it should pass with:
      """
      ............
      ............
      ...111......
      ...1*1......
      ...111......
      ............

      """

  Scenario: Place Two Mines on large Gameboard
    When I run "minesweeper --size=[12,6] --mines=[[5,4],[7,5]]"
    Then it should pass with:
      """
      ............
      ............
      ...111......
      ...1*211....
      ...112*1....
      .....111....

      """

  Scenario: Place Three Mines on large Gameboard
    When I run "minesweeper --size=[12,6] --mines=[[5,4],[7,5],[7,3]]"
    Then it should pass with:
      """
      ............
      .....111....
      ...112*1....
      ...1*322....
      ...112*1....
      .....111....

      """
